SET SERVEROUTPUT ON

SPOOL C:/ORACLEXE/SCRIPTS/SELECTS.TXT

COLUMN ALL_PERSONS FORMAT a15;
COLUMN HIGH_PAID_PERSONS FORMAT a15;
COLUMN PERSONS_OLDER30 FORMAT a15;

SELECT Name AS ALL_PERSONS, SUM(Amount) AS INCOME
FROM TABLE_1 T1 JOIN TABLE_2 T2
ON T1.MemberId = T2.MemberId
GROUP BY Name, T1.MemberId;

SELECT Name AS HIGH_PAID_PERSONS, SUM(Amount) AS INCOME
FROM TABLE_1, TABLE_2
WHERE TABLE_1.MemberId = TABLE_2.MemberId
GROUP BY Name, TABLE_1.MemberId
HAVING SUM(Amount) > 500;

SELECT Name AS PERSONS_OLDER30, SUM(Amount) AS INCOME
FROM TABLE_1, TABLE_2
WHERE TABLE_1.MemberId = TABLE_2.MemberId AND 
	  BirthDate < ADD_MONTHS(CURRENT_DATE, -30 * 12)
GROUP BY  Name, TABLE_1.MemberId;

SPOOL OFF;
