CREATE SEQUENCE seq_MemberId
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	CACHE 4;
	
CREATE TABLE TABLE_1 (
	MemberId INT PRIMARY KEY,
	Name NVARCHAR2(100),
	Address NVARCHAR2(100),
	Mesto NVARCHAR2(100),
	Sex VARCHAR(1) CHECK (Sex IN ('M','W')),
	BirthDate DATE
);

CREATE TABLE TABLE_2 (
	MemberId INT NOT NULL,
	"Date" DATE,
	Amount NUMBER(*,2),
	CONSTRAINT Person_Payment FOREIGN KEY (MemberId) REFERENCES TABLE_1
);
